MAX_GENOME_LENGTH = 100
MIN_GENOME_LENGTH = 1
MUTATION_PROBA = 0.01
ADDITION_PROBA = 0.01
DELETION_PROBA = 0.01
SUBSTITUTION_PROBA = 0.01
SEXUAL_REPRODUCTION_RATE = 0.5
SELF_REPRODUCTION_RATE = 0.5

ALPHABET = ('0', '1')
